### ISSUE TITLE
Carthage reports "Dependency "HueKit" has no shared framework schemes for any of the platforms: iOS"

### ISSUE THREAD

**Issue by icosahedron** [louisdh/huekit#2]
I'm not sure the exact reason, but some research says that the ".xcodeproj/xcshareddata/xcschemes" file should be available for Carthage.  Adding it to the repo for some projects has solved this issue.

**Comment by louisdh** [comment]
Should be solved (b40039e1a3f0b377bc176e4ad632015b622b6576).

**Comment by ilyakooo0** [comment]
I'm still getting `Dependency "huekit" has no shared framework schemes for any of the platforms: iOS`.

(I'm using `--no-use-binaries`)

(Still doesn't work even without it)

**Comment by ilyakooo0** [comment]
I submitted a pull request fixing this issue, but it breaks cocoapods
